### ISSUE TITLE
The step 3 says that pact to rescue is not convinced

### ISSUE THREAD

**Issue by Celthi** [DiUS/pact-workshop-js#10]
The consumer fail in step 2 because it does not follow the API that the provider gives instead consumer tests the API response based on its imagination.

Detail: The provider responses with "validate" but the consumer test "date". So how can the consumer would not fail when connect to the real provider?
So I'm not quite sold. Could anyone help to clear my doubts? Thank you very much!

**Comment by mefellows** [comment]
> So how can the consumer would not fail when connect to the real provider?

It would fail, this is the point 😄 .

This workshop is about illuminating a typical parallel development flow, where multiple teams are pushing to move quickly and have to make assumptions about how they interact as they go, or just simply make honest mistakes.

Pact enables this fast-paced, collaborative development workflow because it ensures both teams are in lock-step during this phase of development and avoids the "integration phase" of projects where all of these problems take ages to sort out.

Later on, when the code is in production, Pact supports continuous delivery and safety, by ensuring that neither party can make a change without ensuring that the change is supported by all parties.

I'm going to close this, because it's really a discussion about pact, not the workshop itself.

**Comment by Celthi** [comment]
@mefellows 
Thank you for your clarification.
