### ISSUE TITLE
The actual code does not verify the full cases.

### ISSUE THREAD

**Issue by Celthi** [DiUS/pact-workshop-js#9]
```
      it('can process the JSON payload from the provider', () => {
        const response = fetchProviderData(submissionDate)

        return expect(response).to.eventually.have.property('count', 0.1)
```

The code(in Consumer.spec.js and ConsumerPact.spec.js) does not verify the 'data' property.
Is it left out for simplicity? Or is it because we can only have one `return expect...`?

If I change the code to 
```
   expect(response).to.eventually.have.property('date2', 'we')  // no return
  return expect(response).to.eventually.have.property('count', 0.1)

```
This code will always pass no matter what the 'date2' or 'date3'
If the code is 
```
   return expect(response).to.eventually.have.property('date2', 'we')  // with return
```
The code will fail.

So al the `expect` without a return in the repo are invalid tests!
I run the test with `npm run test:consumer` and gets the behavior I see above.

**Comment by mefellows** [comment]
I'm not quite sure what you're asking about regarding expectations - that's more of a (chai) framework level question.

But with respect to why do we care about "count" and not "date", the short answer is this: we are _not_ just trying to assert the raw values of the request and response, we are testing the collaborating component (in this case `client.js`) which _just so happens to make a remote call_. It's important, because we are not interested in asserting the entire request/response - we just need the minimum amount from the API that we're interested in.

This particular line does some actual work on the response, https://github.com/DiUS/pact-workshop-js/blob/step3/consumer/client.js#L13, and so we write a unit test to check that behaviour. If the unit test is green, we also know that it made the correct call to the provider.

Under the hood, yes, it makes an HTTP call and pact records what it needs. But in many ways this is less important and is implementation detail.
